openapi: 3.0.0
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'http://backend_server'
info:
  title: Brightcove Beacon API Reference
  description: 'Reference for the Brightcove Beacon API.'
  version: 1.0.0
  x-bc-studio: beacon
servers:
  - url: 'https://beacon.api.brightcove.com/v1'
    variables: {}
tags:
  - name: Apps
    description: Apps related endpoints
  - name: Playlists
    description: Playlists related endpoints
  - name: Pages
    description: Pages related endpoints
  - name: Series
    description: Series related endpoints
  - name: Seasons
    description: Seasons related endpoints
  - name: Genres
    description: Genres related endpoints
  - name: Metadata
    description: Metadata related endpoints
paths:
  '/accounts/{account_id}/apps':
    get:
      tags:
        - Apps
      summary: Get a list of Beacon Apps for this account
      operationId: GetBeaconApps
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/config':
    get:
      tags:
        - Apps
      summary: Configuration options for Beacon Apps
      operationId: GetBeaconAppConfig
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/config/languages':
    get:
      tags:
        - Apps
      summary: List of languages supported by this Beacon app
      operationId: GetAppLanguages
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    put:
      tags:
        - Apps
      summary: Update languages supported by this Beacon app
      operationId: UpdateAppLanguages
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/languages':
    get:
      tags:
        - Apps
      summary: List of all languages supported by this Beacon app
      operationId: GetBeaconAppLanguages
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/plans':
    get:
      tags:
        - Apps
      summary: List all available plans for Beacon Apps
      operationId: GetBeaconPlans
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/series':
    get:
      tags:
        - Series
      summary: Get a list of Series for this account
      operationId: GetAllBeaconSeries
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    post:
      tags:
        - Series
      summary: Create a new Series for this account
      operationId: CreateBeaconSeries
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/series/{series_id}':
    get:
      tags:
        - Series
      summary: Get one Beacon Series for this account
      operationId: GetBeaconSeries
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    put:
      tags:
        - Series
      summary: Update One Beacon Series for this account
      operationId: UpdateBeaconSeries
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    patch:
      tags:
        - Series
      summary: Partially update One Beacon Series for this account
      operationId: PartiallyUpdateBeaconSeries
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    delete:
      tags:
        - Series
      summary: Delete One Beacon Series for this account
      operationId: DeleteBeaconSeries
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/series/{series_id}/seasons':
    get:
      tags:
        - Series
      summary: Get all seasons in one Beacon Series
      operationId: GetBeaconSeriesSeasons
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/series/{series_id}/seasons/{season_id}/episodes':
    get:
      tags:
        - Series
      summary: Get all episodes in one Season in one Beacon Series
      operationId: GetBeaconSeriesSeasonsEpisodes
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/seasons':
    get:
      tags:
        - Seasons
      summary: Get a list of Seasons for this account
      operationId: GetAllBeaconSeasons
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    post:
      tags:
        - Seasons
      summary: Create a new Season for this account
      operationId: CreateBeaconSeason
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/seasons/{season_id}':
    get:
      tags:
        - Seasons
      summary: Get one Beacon Season for this account
      operationId: GetBeaconSeason
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    patch:
      tags:
        - Seasons
      summary: Partially update One Beacon Season for this account
      operationId: PartialUpdateBeaconSeason
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    put:
      tags:
        - Seasons
      summary: Update One Beacon Season for this account
      operationId: UpdateBeaconSeason
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    delete:
      tags:
        - Seasons
      summary: Delete One Beacon Season for this account
      operationId: DeleteBeaconSeason
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/seasons/{season_id}/episodes':
    get:
      tags:
        - Seasons
      summary: Get episodes for one  Beacon Season
      operationId: GetBeaconSeasonEpisodes
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/genres':
    get:
      tags:
        - Genres
      summary: Get a list of Genre for this account
      operationId: GetAllBeaconGenre
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    post:
      tags:
        - Genres
      summary: Create a new Genre or update existing one for this account
      operationId: CreateBeaconGenre
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/genres/{genre_id}':
    get:
      tags:
        - Genres
      summary: Get one Beacon Genre for this account
      operationId: GetBeaconGenre
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/pages':
    get:
      tags:
        - Pages
      summary: Get a list of Pages
      operationId: GetAllBeaconPages
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    post:
      tags:
        - Pages
      summary: Create a new Page
      operationId: CreateBeaconPage
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/pages/{page_id}':
    get:
      tags:
        - Pages
      summary: Get one Beacon Page
      operationId: GetBeaconPages
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    put:
      tags:
        - Pages
      summary: Update One Beacon Page for this account
      operationId: UpdateBeaconPage
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    delete:
      tags:
        - Pages
      summary: Permanently Delete One Beacon Page
      operationId: DeleteBeaconPage
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/pages/{page_id}/archive':
    post:
      tags:
        - Pages
      summary: Archive one Beacon Page
      operationId: ArchiveBeaconPage
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/pages/{page_id}/restore':
    post:
      tags:
        - Pages
      summary: Restore one Beacon Page
      operationId: RestoreBeaconPage
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/pages/{page_id}/rights':
    get:
      tags:
        - Pages
      summary: Get one Beacon Page rights
      operationId: GetBeaconPageRights
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    put:
      tags:
        - Pages
      summary: Update Beacon Page rights
      operationId: UpdateBeaconPageRights
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/pages/{page_id}/images':
    post:
      tags:
        - Pages
      summary: Upload images for a Beacon Page
      operationId: UploadBeaconPageImages
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/users':
    get:
      tags:
        - Users
      summary: Return users by id
      operationId: GetBeaconUsersById
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read            
  '/accounts/{account_id}/apps/{app_id}/users/search':
    get:
      tags:
        - Users
      summary: Return first 10 users containing query string in email and first 10 containing it in the name
      operationId: SearchBeaconUsers
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/users/count':
    get:
      tags:
        - Users
      summary: Return total number of users
      operationId: CountBeaconUsers
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read            
  '/accounts/{account_id}/apps/{app_id}/users/{user_id}':
    get:
      tags:
        - Users
      summary: Get one Beacon User
      operationId: GetBeaconUser
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    delete:
      tags:
        - Users
      summary: Delete one Beacon User and all related data
      operationId: DeleteBeaconUser
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/users/{user_id}/viewinghistory':
    get:
      tags:
        - Users
      summary: Get Users Viewing History
      operationId: GetUserViewingHistory
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/apps/{app_id}/history':
    get:
      tags:
        - History
      summary: Get activity history for a BC Account/App/User
      operationId: GetBcUserHistory
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    post:
      tags:
        - History
      summary: Save one event in activity history for a BC Account/App/User
      operationId: AddBcUserHistory
  '/accounts/{account_id}/apps/{app_id}/users/{user_id}/sessions/{sessions_id}':
    delete:
      tags:
        - Users
      summary: Delete one device session
      operationId: DeleteDeviceSession
  '/accounts/{account_id}/apps/{app_id}/users/{user_id}/profiles/{profile_id}':
    delete:
      tags:
        - Users
      summary: Delete one user's profile
      operationId: DeleteUserProfile
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/cache/{cache_type}':
    post:
      tags:
        - Apps
      summary: Clear Beacon Cache
      operationId: ClearBeaconCache
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/apps/{app_id}/ingestion/{resource_type}':
    post:
      tags:
        - Apps
      summary: Start ingestion of Brightcove content into Beacon
      operationId: BeaconIngestionStart
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
  '/accounts/{account_id}/metadata':
    get:
      tags:
        - Metadata
      summary: Search for metadata through the whole account
      operationId: SearchBeaconMetadata
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
  '/accounts/{account_id}/playlists':
    get:
      tags:
        - Playlists
      summary: Get a list of Playlists for this account
      operationId: GetAllBeaconPlaylists
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
    post:
      tags:
        - Playlists
      summary: Create a new playlists for this account
      operationId: CreateBeaconPlaylists
  '/accounts/{account_id}/playlists/{playlist_id}':
    delete:
      tags:
        - Playlists
      summary: Delete One Beacon playlists for this account
      operationId: DeleteBeaconPlaylists
      security:
        - BC_OAuth2:
            - video-cloud/beacon/all
    patch:
      tags:
        - Playlists
      summary: Update a playlists for this account
      operationId: UpdateBeaconPlaylists
  '/accounts/{account_id}/playlists/search':
    get:
      tags:
        - Playlists
      summary: Return all the playlists containing query string in title or a matched id.
      operationId: SearchBeaconPlaylists
      security:
        - BC_OAuth2:
            - video-cloud/beacon/read
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: 'Brightcove OAuth API. See the [support documentation](https://support.brightcove.com/oauth-api) or [Getting Access Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token) to learn more'
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/beacon/read: Read
            video-cloud/beacon/all: All
